### ISSUE TITLE
Dyskutujemy i dokumentujemy po [PL] czy [ENG]?

### ISSUE THREAD

**Issue by kubamarchwicki** [young-digital-planet/yLibrary#1]
Aby być spójnym :)
Mi to _rybka_ - ale to zawsze moment aby potrenować zanikający dar językowy.

**Comment by Bigismall** [comment]
Wg mnie możemy od razu  przejść na Angielski jeśli chodzi o wiki i dokumentację projektu.
Co ważniejsze ustalenia i tak będziemy poczyniać w YDP twarzą w twarz

**Comment by kubamarchwicki** [comment]
Zatem - agreed!
