### ISSUE TITLE
Potrzeby

### ISSUE THREAD

**Issue by Bigismall** [young-digital-planet/yLibrary#3]
Potrzebuję  barancha **develop**.

Generalnie to fajnie by było gdyby @mpienkowski przydzielił uprawnienia do tworzenia feature branchy. Da się to zrobić na GitHubie?

**Comment by kubamarchwicki** [comment]
Mamy takie uprawnienia. Właśnie to zrobiłem.
git clone
git checkout -b develop
git push origin develop

W ostateczności można pracować na forkach - ale po co sobie utrudniać.

M.

**Comment by Bigismall** [comment]
Ja pracuję z GIT Ext,  ale rzeczywiście teraz mi się udało. wcześniej zakombinowałem chyba.

Co do modelu pracy, to ja proponuję tak jak to opisał Czarek.  Tworzenie Forków wewnątrz jednego zespołu to trochę przerost :|
